spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: Pranavtomar@1620
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    net:
      engineeringdigest:
        journalApp: INFO

weather:
  api:
    key: 17cc1c4c43afaea56386bbae384de7d0



#logging:
#  level:
#    root: Error

#logging:
#  level:
#    net:
#      engineeringdigest:
#        journalApp:
#          service:
#            UserService: OFF

