spring:
  profiles:
    active: dev

logging:
  level:
    net:
      engineeringdigest:
        journalApp: INFO



weather:
  api:
    key: 17cc1c4c43afaea56386bbae384de7d0



#logging:
#  level:
#    root: Error

#logging:
#  level:
#    net:
#      engineeringdigest:
#        journalApp:
#          service:
#            UserService: OFF

