
spring:
  data:
    mongodb:
      uri: mongodb+srv://alokpranavsingh11619:Pranavtomar%401620@cluster0.9iqxy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journalDB
      auto-index-creation: true
  application:
    name: journalApp

server:
  port: 8080
  servlet:
    context-path: /journal

